version: '2'

services:
  web:
    container_name: php-apache
    build: ./php-apache
    ports:
      - 80:80
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./src/:/var/www/html
  
  db:
    build: ./mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: test
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: test
    volumes:
      - ./db:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8080:80
   
volumes:
  src:
    driver: local
  db:
    driver: local
